### ISSUE TITLE
HTTP sink GET request fails with HTTP 400

### ISSUE THREAD

**Issue by tishan89** [wso2-extensions/siddhi-io-http#99] opened 2018-12-13 05:49 UTC
**Description:**
HTTP sink GET request fails with HTTP 400 because we are not sending in Host header. Need to follow up on this and investigate why we are not sending Host header and what to be expected as per spec

**Affected Product Version:**
SP 4.x.x  

**Steps to reproduce:**
Can use below Siddhi App to reproduce

```
@App:name("SiddhiApp")
@App:description("Description of the plan")

-- Please refer to https://docs.wso2.com/display/SP400/Quick+Start+Guide on getting started with SP editor. 

@sink(
    type='http-request', sink.id='id1', publisher.url='http://api.worldbank.org/v2/countries/all/indicators/SP.POP.TOTL', 
    method='GET', headers = "'Host:api.worldbank.org'",
    @map(type='json'))
define stream FooStream (payloadBody String);

@source(type='http-response', sink.id='id1', http.status.code='200',@map(type='text' ))
@sink(type = 'log', prefix = 'LOGGER')
define stream responseStream2xx(body string);

@source(type='http-response', sink.id='id1', http.status.code='400', @map(type='text'))
@sink(type = 'log', prefix = 'LOGGER')
define stream responseStream4xx(body string);
```

**Comment by Niveathika92** [comment] 2018-12-13 07:07
Duplicate of https://github.com/wso2-extensions/siddhi-io-http/issues/82, the fix is available from version 1.0.40

**Closed by Niveathika92** 2018-12-13 07:07 UTC
Labels: Priority/High, Severity/Critical, bug
